# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graphics-ColorUtils
version:      0.03
version_from: lib/Graphics/ColorUtils.pm
installdirs:  site
requires:
    Carp:                          

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
